apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: default # Service lives in the same namespace
spec:
  selector:
    app: petclinic # Selects pods with the 'app: petclinic' label
  ports:
    - protocol: TCP
      port: 80       # Cluster-internal port the service listens on
      targetPort: 8080 # Port inside the container to route traffic to
      # --- Add this line ---
      nodePort: 30080  # Specific port exposed on the Node
  # --- Change this line ---
  type: NodePort # Exposes the service on each Node's IP at a static port
