apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  namespace: default # Service lives in the same namespace
spec:
  selector:
    app: petclinic # Selects pods with the 'app: petclinic' label
  ports:
    - protocol: TCP
      port: 80       # Expose the service on port 80 (standard HTTP)
      targetPort: 8080 # Route traffic to port 8080 on the pods
  # Type LoadBalancer tells AWS to create an Elastic Load Balancer
  # to expose this service publicly outside the cluster.
  type: LoadBalancer
